### ISSUE TITLE
Unable to compile with nginx 1.11.1

### ISSUE THREAD

**Issue by Fank** [arut/nginx-rtmp-module#823]
```
/opt/nginx-rtmp-module/ngx_rtmp_core_module.c:548:9: error: cannot convert to a pointer type
         if (ngx_memcmp(ls[i].sockaddr + off, u.sockaddr + off, len) != 0) {
         ^
In file included from src/core/ngx_core.h:51:0,
                 from /opt/nginx-rtmp-module/ngx_rtmp_core_module.c:8:
src/core/ngx_string.h:102:42: error: incompatible type for argument 2 of ‘memcpy’
 #define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                          ^
/opt/nginx-rtmp-module/ngx_rtmp_core_module.c:568:5: note: in expansion of macro ‘ngx_memcpy’
     ngx_memcpy(ls->sockaddr, u.sockaddr, u.socklen);
     ^
In file included from src/os/unix/ngx_linux_config.h:27:0,
                 from src/core/ngx_config.h:26,
                 from /opt/nginx-rtmp-module/ngx_rtmp_core_module.c:7:
/usr/include/string.h:46:14: note: expected ‘const void * __restrict__’ but argument is of type ‘ngx_sockaddr_t’
 extern void *memcpy (void *__restrict __dest, const void *__restrict __src,
              ^
objs/Makefile:1390: recipe for target 'objs/addon/nginx-rtmp-module/ngx_rtmp_core_module.o' failed
make[1]: *** [objs/addon/nginx-rtmp-module/ngx_rtmp_core_module.o] Error 1
make[1]: Leaving directory '/opt/nginx-1.11.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

configure:
`./configure --prefix=/usr/local/nginx --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_dav_module --with-http_mp4_module --with-openssl=/opt/openssl-1.0.2h --add-module=/opt/nginx-rtmp-module --add-module=/opt/nginx-dav-ext-module`

**Comment by jeoliva** [comment]
#820

**Comment by arut** [comment]
fixed, thanks
