### ISSUE TITLE
Compiling nginx 1.10.3: undefined reference to `SSL_get0_alpn_selected' and `SSL_CTX_set_alpn_select_cb'

### ISSUE THREAD

**Issue by cricsus** [arut/nginx-rtmp-module#996]
On my Debian Jessie (x86_64), I have been trying to both `dpkg-buildpackage` and compile using `make` using the nginx sources. The reason for me using this method than just using `apt-get` is, so that nginx compiles with the just compiled OpenSSL 1.0.2k so that I can enable HTTP/2 on my already existing server (`apt-get install --reinstall nginx` is useless in that matter and I'd like to keep my configs).

However, each time I try it, the following error occurs:

> objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_check_host':
> /build/nginx-local/nginx-src/nginx-1.10.3/src/event/ngx_event_openssl.c:2997: undefined reference to `X509_check_host'
> objs/src/http/ngx_http_request.o: In function `ngx_http_ssl_handshake_handler':
> /build/nginx-local/nginx-src/nginx-1.10.3/src/http/ngx_http_request.c:780: undefined reference to `SSL_get0_alpn_selected'
> objs/src/http/modules/ngx_http_ssl_module.o: In function `ngx_http_ssl_merge_srv_conf':
> /build/nginx-local/nginx-src/nginx-1.10.3/src/http/modules/ngx_http_ssl_module.c:653: undefined reference to `SSL_CTX_set_alpn_select_cb'
> collect2: error: ld returned 1 exit status
> objs/Makefile:302: recipe for target 'objs/nginx' failed
> make[1]: *** [objs/nginx] Error 1
> make[1]: Leaving directory '/build/nginx-local/nginx-src/nginx-1.10.3'
> Makefile:8: recipe for target 'build' failed
> make: *** [build] Error 2

FYI, I used the following to configure:

> $ ./configure --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-file-aio --with-threads --with-ipv6 --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_ssl_module --with-cc-opt='-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

Thenafter the usual `make`
_________

If there was an already resolved issue like this reported and I couldn't find it, please pardon this issue. But I'll be grateful for any help :)

**Comment by PropTim** [comment]
Also with 1.12-stable and 1.13 using OpenSSL 1.1.0e

```-ldl -lpthread -lcrypt -lpcre -lssl -lcrypto -ldl -lz -lGeoIP \
-Wl,-E
objs/src/core/nginx.o: In function `ngx_show_version_info':
/root/nginx/src/core/nginx.c:424: undefined reference to `SSLeay_version'
/root/nginx/src/core/nginx.c:429: undefined reference to `SSLeay_version'
objs/src/event/ngx_event_openssl.o: In function `ngx_openssl_exit':
/root/nginx/src/event/ngx_event_openssl.c:4203: undefined reference to `EVP_cleanup'
/root/nginx/src/event/ngx_event_openssl.c:4205: undefined reference to `ENGINE_cleanup'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_init':
/root/nginx/src/event/ngx_event_openssl.c:140: undefined reference to `SSL_library_init'
/root/nginx/src/event/ngx_event_openssl.c:141: undefined reference to `SSL_load_error_strings'
/root/nginx/src/event/ngx_event_openssl.c:143: undefined reference to `OPENSSL_add_all_algorithms_noconf'
/root/nginx/src/event/ngx_event_openssl.c:167: undefined reference to `SSL_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:174: undefined reference to `SSL_CTX_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:182: undefined reference to `SSL_CTX_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:190: undefined reference to `SSL_CTX_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:198: undefined reference to `SSL_CTX_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:206: undefined reference to `X509_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:213: undefined reference to `X509_get_ex_new_index'
/root/nginx/src/event/ngx_event_openssl.c:221: undefined reference to `X509_get_ex_new_index'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_create':
/root/nginx/src/event/ngx_event_openssl.c:235: undefined reference to `SSLv23_method'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_ciphers':
/root/nginx/src/event/ngx_event_openssl.c:649: undefined reference to `SSL_CTX_set_tmp_rsa_callback'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_shutdown':
/root/nginx/src/event/ngx_event_openssl.c:1906: undefined reference to `SSL_state'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_session_id_context':
/root/nginx/src/event/ngx_event_openssl.c:2299: undefined reference to `EVP_MD_CTX_create'
/root/nginx/src/event/ngx_event_openssl.c:2336: undefined reference to `sk_num'
/root/nginx/src/event/ngx_event_openssl.c:2339: undefined reference to `sk_value'
/root/nginx/src/event/ngx_event_openssl.c:2361: undefined reference to `EVP_MD_CTX_destroy'
/root/nginx/src/event/ngx_event_openssl.c:2373: undefined reference to `EVP_MD_CTX_destroy'
objs/src/event/ngx_event_openssl.o: In function `ngx_ssl_check_host':
/root/nginx/src/event/ngx_event_openssl.c:3205: undefined reference to `sk_num'
/root/nginx/src/event/ngx_event_openssl.c:3208: undefined reference to `sk_value'
objs/src/event/ngx_event_openssl_stapling.o: In function `ngx_ssl_stapling_issuer':
/root/nginx/src/event/ngx_event_openssl_stapling.c:308: undefined reference to `sk_num'
/root/nginx/src/event/ngx_event_openssl_stapling.c:314: undefined reference to `sk_value'
/root/nginx/src/event/ngx_event_openssl_stapling.c:319: undefined reference to `CRYPTO_add_lock'
objs/src/event/ngx_event_openssl_stapling.o: In function `ngx_ssl_stapling_responder':
/root/nginx/src/event/ngx_event_openssl_stapling.c:404: undefined reference to `sk_value'
collect2: error: ld returned 1 exit status
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory `/root/nginx'
make: *** [build] Error 2```
