### ISSUE TITLE
Windows compilation error

### ISSUE THREAD

**Issue by Jack0r** [arut/nginx-rtmp-module#545]
Hey,
I had posted to the google group but got no response so far. Hope maybe someone here can fix this error:
objs/lib/nginx-rtmp-module/ngx_rtmp.c(841) : error C2220: warning treated as error - no 'object' file generated
objs/lib/nginx-rtmp-module/ngx_rtmp.c(841) : warning C4090: '=' : different 'volatile' qualifiers
objs/lib/nginx-rtmp-module/ngx_rtmp.c(841) : warning C4090: '=' : different 'volatile' qualifiers
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\BIN\cl.EXE"' : return code '0x2'
Stop.

Tried to compile with nginx 1.7.7. If you need any further info, I would be happy to give it to you!
